version: '3.7'
services:

  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user" ]
      interval: 10s
      timeout: 5s
      retries: 5