micronaut:
  application:
    name: backend-bike
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: test_user
    password: test_password
jpa.default.properties.hibernate.hbm2ddl.auto: validate
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.sql


# FEATURE FLAGS: set these variables to enable/disable the features that we activate
feature:
  # the type of persistence that we support
  # MEMORY (DEFAULT): stored in the app's RAM
  # ORM: using postgres with the JPA ORM on top
  # STORED_PROC: using postgres stored procedure directly without any ORM layers
  persistence: ORM